CREATE TABLE blacklist(
    blacklistID TEXT PRIMARY KEY,
    hashed TEXT UNIQUE NOT NULL,
    blacklistedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE logs(
    userID TEXT NOT NULL,
    modAction TEXT NOT NULL,
    actionTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    target TEXT
);
CREATE TABLE pinned(
    messageID TEXT PRIMARY KEY,
    userID TEXT NOT NULL,
    pinnedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);